version: "3"

services:
  database:
    image: library/postgres:latest
    environment:
      POSTGRES_USER: 'marten'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'marten'
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
